### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arkon** [arkon/uoft-enrolment-charts#2]
- [ ] Improve performance (multithread?)
- [x] Cron job to fetch data using https://github.com/freeatnet/uoft-timetable-archive + generate charts + push
- [x] Better looking charts
- [ ] More data: waitlist, available spots
- [x] Website?
- [ ] Make website not terrible

**Comment by naviechan** [comment]
Would be cool if you plot the waitlist size on top of number of students enrolled.

**Comment by arkon** [comment]
@naviechan You mean having it on the graph as well, or added together?

**Comment by naviechan** [comment]
@arkon I was thinking about displaying aggregated numbers. And then draw a vertical line on the day which the waitlist closes so that people will understand why the number drops all the sudden.

**Comment by arkon** [comment]
Closing this in favour of separate issues.
